<a href="https://colab.research.google.com/github/venkat2ram/Keras-and-Tensorflow/blob/master/simple_neural_network_TF_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from random import randint
import numpy as np
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler


Create a sample data set with 2100 reecords whith ages between 13 to 100. 
For ages 13-64, there shuould be 5% data with label 1.
For ages 65-100, there should be 95% data with label 1.

In [28]:
train_samples=[]
train_labels=[]

#50 samples each for impacted youth and not impacted old age people.
for i in range(50):
  rand_young_noimpact=randint(13,64)
  train_samples.append(rand_young_noimpact)
  train_labels.append(1)

  rand_old_impact=randint(65,100)
  train_samples.append(rand_old_impact)
  train_labels.append(0)


#1000 samples each for impacted youth and not impacted old age people.
for i in range(1000):
  rand_young_noimpact=randint(13,64)
  train_samples.append(rand_young_noimpact)
  train_labels.append(0)

  rand_old_impact=randint(65,100)
  train_samples.append(rand_old_impact)
  train_labels.append(1)


Shuffle the data.

In [29]:

train_samples=np.array(train_samples)
train_labels=np.array(train_labels)
train_samples,train_labels=shuffle(train_samples,train_labels)

In [30]:
scaler=MinMaxScaler(feature_range=(0,1))
scaled_train_samples=scaler.fit_transform(train_samples.reshape(-1,1))

**Prepare test data.**

In [31]:
test_samples=[]
test_labels=[]

#50 samples each for impacted youth and not impacted old age people.
for i in range(10):
  rand_young_noimpact=randint(13,64)
  test_samples.append(rand_young_noimpact)
  test_labels.append(1)

  rand_old_impact=randint(65,100)
  test_samples.append(rand_old_impact)
  test_labels.append(0)


#1000 samples each for impacted youth and not impacted old age people.
for i in range(200):
  rand_young_noimpact=randint(13,64)
  test_samples.append(rand_young_noimpact)
  test_labels.append(0)

  rand_old_impact=randint(65,100)
  test_samples.append(rand_old_impact)
  test_labels.append(1)

In [32]:
test_samples=np.array(test_samples)
test_labels=np.array(test_labels)
test_samples,test_labels=shuffle(test_samples,test_labels)

In [33]:
scaler=MinMaxScaler(feature_range=(0,1))
scaled_test_samples=scaler.fit_transform(test_samples.reshape(-1,1))

**Train model**

In [34]:
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import sparse_categorical_crossentropy
from tensorflow.keras.metrics import categorical_crossentropy

In [35]:
import keras

In [36]:
model=Sequential([
    Dense(16,input_shape=(1,), activation='relu'),
    Dense(32,activation='relu'),
    Dense(2,activation='softmax')]
)

In [37]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.compile(Adam(lr=0.0001), loss='sparse_categorical_crossentropy',metrics='accuracy')

In [39]:
model.fit(scaled_train_samples,train_labels,validation_split=0.2,batch_size=10,epochs=20,verbose=2)

Epoch 1/20
168/168 - 0s - loss: 0.6768 - accuracy: 0.5286 - val_loss: 0.6651 - val_accuracy: 0.5357
Epoch 2/20
168/168 - 0s - loss: 0.6540 - accuracy: 0.6042 - val_loss: 0.6377 - val_accuracy: 0.6357
Epoch 3/20
168/168 - 0s - loss: 0.6290 - accuracy: 0.6613 - val_loss: 0.6120 - val_accuracy: 0.6976
Epoch 4/20
168/168 - 0s - loss: 0.6022 - accuracy: 0.7155 - val_loss: 0.5779 - val_accuracy: 0.7548
Epoch 5/20
168/168 - 0s - loss: 0.5739 - accuracy: 0.7548 - val_loss: 0.5493 - val_accuracy: 0.7857
Epoch 6/20
168/168 - 0s - loss: 0.5486 - accuracy: 0.7768 - val_loss: 0.5213 - val_accuracy: 0.8286
Epoch 7/20
168/168 - 0s - loss: 0.5242 - accuracy: 0.7929 - val_loss: 0.4941 - val_accuracy: 0.8405
Epoch 8/20
168/168 - 0s - loss: 0.5005 - accuracy: 0.8054 - val_loss: 0.4677 - val_accuracy: 0.8667
Epoch 9/20
168/168 - 0s - loss: 0.4780 - accuracy: 0.8280 - val_loss: 0.4426 - val_accuracy: 0.8881
Epoch 10/20
168/168 - 0s - loss: 0.4567 - accuracy: 0.8381 - val_loss: 0.4191 - val_accuracy: 0.9000

**Predict:**

In [44]:
predict=model.predict(scaled_test_samples,batch_size=10)

In [46]:
predict_class=model.predict_classes(scaled_test_samples,batch_size=10)

Confusion_matrix

In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
cm=confusion_matrix(test_labels,predict_class)

In [49]:
cm

array([[188,  22],
       [ 10, 200]])

**Saving model:**

**Saving complete model:**

save function saves whole model with configuration, learning rate, optimizer and weights etc.*italicized text*

In [52]:
from tensorflow.keras.models import load_model

In [53]:
model.save('model.h5')

In [54]:
model2=load_model('model.h5')

In [58]:
model2.get_weights()

[array([[ 0.42772338, -0.31154543, -0.54696333,  0.71126103, -0.3378055 ,
          0.18009143, -0.4471144 ,  0.2249354 , -0.06448126,  0.4205414 ,
         -0.18344235,  0.33340186, -0.3092667 ,  0.43717766,  0.25347683,
         -0.23293298]], dtype=float32),
 array([-0.1120466 ,  0.        ,  0.        , -0.10683451,  0.        ,
         0.20941758,  0.        , -0.06869689,  0.        , -0.10329426,
         0.        ,  0.15045851,  0.        , -0.10100259, -0.07723005,
         0.        ], dtype=float32),
 array([[ 6.68734387e-02,  1.18522495e-01,  3.12476844e-01,
          6.82360306e-03, -1.32089695e-02,  4.49052334e-01,
         -4.95532602e-02, -2.54679412e-01,  1.72349632e-01,
          6.98941350e-02, -3.54850680e-01, -1.31661192e-01,
          1.97685018e-01,  4.23505336e-01, -1.03696838e-01,
         -1.16964579e-01,  3.53599899e-02, -4.28963900e-02,
         -7.36173093e-02,  4.36895013e-01,  2.39113465e-01,
          2.43710056e-01,  1.77939981e-01,  5.22106647e-01,
 

In [57]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [61]:
model2.optimizer

**to_json()**

to_json() saves only the configuration of the model. configuration includes only layer information. not weights and training information.

In [64]:
model_json=model.to_json()

In [66]:
from tensorflow.keras.models import model_from_json

In [67]:
model3=model_from_json(model_json)

In [69]:
model3.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


**save_weights()**

save_weights() function saves only the weights of the model. to use these weights you need define the model again with layer details.

In [75]:
model.save_weights('model_weights.h5')

In [76]:
model4=Sequential([
    Dense(16,input_shape=(1,), activation='relu'),
    Dense(32,activation='relu'),
    Dense(2,activation='softmax')]
)

In [77]:
model4.load_weights('model_weights.h5')

In [79]:
model.get_weights()

[array([[ 0.42772338, -0.31154543, -0.54696333,  0.71126103, -0.3378055 ,
          0.18009143, -0.4471144 ,  0.2249354 , -0.06448126,  0.4205414 ,
         -0.18344235,  0.33340186, -0.3092667 ,  0.43717766,  0.25347683,
         -0.23293298]], dtype=float32),
 array([-0.1120466 ,  0.        ,  0.        , -0.10683451,  0.        ,
         0.20941758,  0.        , -0.06869689,  0.        , -0.10329426,
         0.        ,  0.15045851,  0.        , -0.10100259, -0.07723005,
         0.        ], dtype=float32),
 array([[ 6.68734387e-02,  1.18522495e-01,  3.12476844e-01,
          6.82360306e-03, -1.32089695e-02,  4.49052334e-01,
         -4.95532602e-02, -2.54679412e-01,  1.72349632e-01,
          6.98941350e-02, -3.54850680e-01, -1.31661192e-01,
          1.97685018e-01,  4.23505336e-01, -1.03696838e-01,
         -1.16964579e-01,  3.53599899e-02, -4.28963900e-02,
         -7.36173093e-02,  4.36895013e-01,  2.39113465e-01,
          2.43710056e-01,  1.77939981e-01,  5.22106647e-01,
 

**Rough work:**

In [ ]:
train_labels